version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8

  tf-init:
    commands:
      - terraform init

  tf-validade:
    commands:
      - terraform validate

  tf-plan:
    commands:
      - terraform plan